spring:
    application:
        name: url-shortener
    datasource:
        url: jdbc:postgresql://localhost:5432/urlshortener
        username: urlshortener
        password: localdev
    jpa:
        hibernate:
            ddl-auto: validate